# Build settings
[build]
  # Define o diretório de construção para a pasta interface
  base = "interface"
  # Comando de construção, se necessário
  command = "npm run build" # ou o comando correspondente para construir o front-end

# Configuração do diretório público
publish = "interface/public" # ou o diretório correspondente onde os arquivos estáticos serão gerados após a construção

# Redirects and rewrites
[[redirects]]
  # Redireciona todas as solicitações para o index.js (para o roteamento no servidor)
  from = "/*"
  to = "/index.js"
  status = 200

# Redirect para a página inicial
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200
